import asyncio
import subprocess
from typing import Dict, Any

class ExecutionRunner:
    """
    Executes tasks generated by the orchestrator.
    In a real system, this could run python code, shell scripts, or API calls.
    """
    
    async def run_command(self, command: str) -> Dict[str, Any]:
        """
        Runs a shell command and returns the output and exit code.
        """
        process = await asyncio.create_subprocess_shell(
            command,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE
        )
        
        stdout, stderr = await process.communicate()
        
        return {
            "success": process.returncode == 0,
            "stdout": stdout.decode().strip(),
            "stderr": stderr.decode().strip(),
            "exit_code": process.returncode
        }

    async def execute_task(self, task_description: str) -> Dict[str, Any]:
        """
        Parses the task description and executes it.
        """
        desc_lower = task_description.lower()
        if "sql" in desc_lower and ("interpolation" in desc_lower or "raw" in desc_lower or "select" in desc_lower or "concat" in desc_lower):
            return {
                "success": False,
                "stdout": "",
                "stderr": "SQL INJECTION ERROR: Raw input interpolation detected in database query compiler. Injection string pattern found: ' OR 1=1 --",
                "exit_code": 1
            }
        elif "privileged" in desc_lower or "hostpath" in desc_lower or "cron-job" in desc_lower:
            return {
                "success": False,
                "stdout": "",
                "stderr": "SECURITY ERROR: hostPath mount and privileged securityContext are blocked by GKE admission controller policies.",
                "exit_code": 1
            }
        elif "docker.sock" in desc_lower or "root privileges" in desc_lower or "socket binding" in desc_lower or "root user" in desc_lower:
            return {
                "success": False,
                "stdout": "",
                "stderr": "PERMISSIONS ERROR: Docker socket mounting and root user executions are prohibited under container runtime sandboxing rules.",
                "exit_code": 1
            }

        # Simulating simple command execution if the task looks like a command
        if task_description.startswith("run:"):
            command = task_description[4:].strip()
            return await self.run_command(command)
            
        return {
            "success": True,
            "message": f"Executed natural language task: {task_description}",
            "data": None
        }
